name: Build and deploy JAR app to Azure Web App - citicita

on:
  push:
    branches:
      - deneme9
  workflow_dispatch:

env:
  DB_USERNAME: postgres
  DB_PASSWORD: root
  DB_NAME: chatbotdb2
  DB_URL: "jdbc:postgresql://localhost:5432/chatbotdb2?sslmode=require"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql
          sudo service postgresql start  
          sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME};"
          sudo -u postgres psql -c "ALTER USER ${DB_USERNAME} PASSWORD '${DB_PASSWORD}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USERNAME};"
          PGPASSWORD="${DB_PASSWORD}" psql -h localhost -U ${DB_USERNAME} -d ${DB_NAME} -c "SELECT 1" || exit 1


      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_122D2C15DC8747E1B5B16FE84476B980 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1023DE9B73924D749B575913BBF049FE}}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2A380D5DD3104D0D83CEB92D52EB8D3D}}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'citicita'
          slot-name: 'Production'
          package: '*.jar'
